"""Create order_product_association relation

Revision ID: f291ead6acb9
Revises: ce2896d4ee1c
Create Date: 2025-03-03 13:44:44.677179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f291ead6acb9"
down_revision: Union[str, None] = "ce2896d4ee1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
