"""add count column in order_product_association

Revision ID: 48caf4fe0964
Revises: 562180e3ed19
Create Date: 2025-03-03 17:50:20.742490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48caf4fe0964"
down_revision: Union[str, None] = "562180e3ed19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "src_order_product_association",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("src_order_product_association", "count")
    # ### end Alembic commands ###
