"""Create Profile table

Revision ID: 0254f209e5be
Revises: 3275338efda5
Create Date: 2025-03-01 14:22:19.067590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0254f209e5be"
down_revision: Union[str, None] = "3275338efda5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "src_profile",
        sa.Column("firstname", sa.String(length=50), server_default="", nullable=False),
        sa.Column("lastname", sa.String(length=50), server_default="", nullable=False),
        sa.Column("bio", sa.Text(), server_default="", nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["src_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("src_profile")
    # ### end Alembic commands ###
