"""add columns to users

Revision ID: 32f572efef3b
Revises: e6eeac583a0e
Create Date: 2025-03-05 11:42:10.870915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32f572efef3b"
down_revision: Union[str, None] = "e6eeac583a0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "src_user",
        sa.Column("password", sa.String(), server_default="UN", nullable=False),
    )
    op.add_column("src_user", sa.Column("email", sa.String(), nullable=True))
    op.add_column(
        "src_user",
        sa.Column("is_active", sa.Boolean(), server_default="True", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("src_user", "is_active")
    op.drop_column("src_user", "email")
    op.drop_column("src_user", "password")
    # ### end Alembic commands ###
